version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: test-username
      MONGO_INITDB_ROOT_PASSWORD: test-password
  
  mongosh:
    image: mongo:latest
    command: mongosh --host mongodb:27017 -u test-username -p test-password --authenticationDatabase admin
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
